model_type: t5
model_name_or_path: t5-small
output_dir: ./output_generator
overwrite_output_dir: true
per_device_train_batch_size: 4
num_train_epochs: 3
save_steps: 500
save_total_limit: 2
logging_dir: ./logs_generator
logging_steps: 100
