model_type: rag-token
model_name_or_path: facebook/rag-token-base
output_dir: ./output_retriever
overwrite_output_dir: true
per_device_train_batch_size: 4
num_train_epochs: 3
save_steps: 500
save_total_limit: 2
logging_dir: ./logs_retriever
logging_steps: 100
